CREATE TABLE IZVODAC
(
  IDIzvodaca SERIAL NOT NULL,
  NazivIzvodaca VARCHAR(50) NOT NULL,
  OpisIzvodaca TEXT,
  PRIMARY KEY (IDIzvodaca)
);

CREATE TABLE ALBUM
(
  IDAlbuma SERIAL NOT NULL,
  NazivAlbuma VARCHAR(100) NOT NULL,
  DatumIzdavanja DATE NOT NULL,
  OpisAlbuma TEXT,
  IDIzvodaca INT NOT NULL,
  PRIMARY KEY (IDAlbuma),
  FOREIGN KEY (IDIzvodaca) REFERENCES IZVODAC(IDIzvodaca)
);

CREATE TABLE PJESMA
(
  IDPjesme SERIAL NOT NULL,
  NazivPjesme VARCHAR(50) NOT NULL,
  Trajanje TIME NOT NULL,
  IDIzvodaca INT NOT NULL,
  IDAlbuma INT,
  PRIMARY KEY (IDPjesme),
  FOREIGN KEY (IDIzvodaca) REFERENCES IZVODAC(IDIzvodaca),
  FOREIGN KEY (IDAlbuma) REFERENCES ALBUM(IDAlbuma)
);

CREATE TABLE LOKACIJA
(
  Drzava VARCHAR(100) NOT NULL,
  Grad VARCHAR(100) NOT NULL,
  PostanskiBroj VARCHAR(20) NOT NULL,
  Adresa VARCHAR(100) NOT NULL,
  IDLokacije SERIAL NOT NULL,
  PRIMARY KEY (IDLokacije)
);

CREATE TABLE ADMINISTRATOR
(
  IDAdministratora SERIAL NOT NULL,
  EmailAdresa VARCHAR(100) NOT NULL,
  HashLozinke VARCHAR(255) NOT NULL,
  Ime VARCHAR(50) NOT NULL,
  Prezime VARCHAR(50) NOT NULL,
  KorisnickoIme VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDAdministratora),
  UNIQUE (EmailAdresa),
  UNIQUE (KorisnickoIme)
);

CREATE TABLE ORGKONCERATA
(
  IDOrgKoncerata SERIAL NOT NULL,
  EmailAdresa VARCHAR(100) NOT NULL,
  HashLozinke VARCHAR(255) NOT NULL,
  Ime VARCHAR(50) NOT NULL,
  Prezime VARCHAR(50) NOT NULL,
  KorisnickoIme VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDOrgKoncerata),
  UNIQUE (EmailAdresa),
  UNIQUE (KorisnickoIme)
);

CREATE TABLE LJUBITELJGLAZBE
(
  IDLjubiteljaGlazb SERIAL NOT NULL,
  EmailAdresa VARCHAR(100) NOT NULL,
  HashLozinke VARCHAR(255) NOT NULL,
  Ime VARCHAR(50) NOT NULL,
  Prezime VARCHAR(50) NOT NULL,
  KorisnickoIme VARCHAR(50) NOT NULL,
  Pretplacen BOOLEAN NOT NULL DEFAULT TRUE,
  IDLokacije INT NOT NULL,
  PRIMARY KEY (IDLjubiteljaGlazb),
  FOREIGN KEY (IDLokacije) REFERENCES LOKACIJA(IDLokacije),
  UNIQUE (EmailAdresa),
  UNIQUE (KorisnickoIme)
);

CREATE TABLE KONCERT
(
  IDKoncerta SERIAL NOT NULL,
  NazivKoncerta VARCHAR(50) NOT NULL,
  VrijemeOdrzava TIMESTAMP NOT NULL,
  OpisKoncerta TEXT,
  IDOrgKoncerata INT NOT NULL,
  IDLokacije INT NOT NULL,
  IDIzvodaca INT NOT NULL,
  PRIMARY KEY (IDKoncerta),
  FOREIGN KEY (IDOrgKoncerata) REFERENCES ORGKONCERATA(IDOrgKoncerata),
  FOREIGN KEY (IDLokacije) REFERENCES LOKACIJA(IDLokacije),
  FOREIGN KEY (IDIzvodaca) REFERENCES IZVODAC(IDIzvodaca)
);

CREATE TABLE TVRTKA
(
  IDTvrtke SERIAL NOT NULL,
  VAT VARCHAR(30) NOT NULL,
  NazivTvrtke VARCHAR(200) NOT NULL,
  PRIMARY KEY (IDTvrtke),
  UNIQUE (VAT)
);

CREATE TABLE OBAVIJEST (
    IDObavijesti SERIAL NOT NULL,
    IDLjubiteljaGlazb INT NOT NULL,
    IDKoncerta INT NOT NULL,
    VrijemeSlanja TIMESTAMP NOT NULL,
    PRIMARY KEY (IDObavijesti),
    FOREIGN KEY (IDLjubiteljaGlazb) REFERENCES LJUBITELJGLAZBE(IDLjubiteljaGlazb),
    FOREIGN KEY (IDKoncerta) REFERENCES KONCERT(IDKoncerta),
    UNIQUE (IDLjubiteljaGlazb, IDKoncerta)
);

CREATE TABLE STATKONCERTA
(
  BrStatistike SERIAL NOT NULL,
  UkBrKorisnika INT NOT NULL,
  BrKorPoGradu INT NOT NULL,
  VrijemeGen TIMESTAMP NOT NULL,
  IDKoncerta INT NOT NULL,
  PRIMARY KEY (BrStatistike, IDKoncerta),
  FOREIGN KEY (IDKoncerta) REFERENCES KONCERT(IDKoncerta)
);

CREATE TABLE ZANR
(
  IDZanra SERIAL NOT NULL,
  NazivZanra VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDZanra)
);

CREATE TABLE LEGITORGKONCERT
(
  IDLegitOrg SERIAL NOT NULL,
  Ime VARCHAR(50) NOT NULL,
  Prezime VARCHAR(50) NOT NULL,
  EmailAdresa VARCHAR(100) NOT NULL,
  IDTvrtke INT,
  PRIMARY KEY (IDLegitOrg),
  FOREIGN KEY (IDTvrtke) REFERENCES TVRTKA(IDTvrtke),
  UNIQUE (EmailAdresa)
);

CREATE TABLE SESVIDAIZVODAC
(
  IDLjubiteljaGlazb INT NOT NULL,
  IDIzvodaca INT NOT NULL,
  PRIMARY KEY (IDLjubiteljaGlazb, IDIzvodaca),
  FOREIGN KEY (IDLjubiteljaGlazb) REFERENCES LJUBITELJGLAZBE(IDLjubiteljaGlazb),
  FOREIGN KEY (IDIzvodaca) REFERENCES IZVODAC(IDIzvodaca)
);

CREATE TABLE SESVIDAALBUM
(
  IDLjubiteljaGlazb INT NOT NULL,
  IDAlbuma INT NOT NULL,
  PRIMARY KEY (IDLjubiteljaGlazb, IDAlbuma),
  FOREIGN KEY (IDLjubiteljaGlazb) REFERENCES LJUBITELJGLAZBE(IDLjubiteljaGlazb),
  FOREIGN KEY (IDAlbuma) REFERENCES ALBUM(IDAlbuma)
);

CREATE TABLE SESVIDAPJESMA
(
  IDLjubiteljaGlazb INT NOT NULL,
  IDPjesme INT NOT NULL,
  PRIMARY KEY (IDLjubiteljaGlazb, IDPjesme),
  FOREIGN KEY (IDLjubiteljaGlazb) REFERENCES LJUBITELJGLAZBE(IDLjubiteljaGlazb),
  FOREIGN KEY (IDPjesme) REFERENCES PJESMA(IDPjesme)
);

CREATE TABLE DOLAZI
(
  IDLjubiteljaGlazb INT NOT NULL,
  IDKoncerta INT NOT NULL,
  PRIMARY KEY (IDLjubiteljaGlazb, IDKoncerta),
  FOREIGN KEY (IDLjubiteljaGlazb) REFERENCES LJUBITELJGLAZBE(IDLjubiteljaGlazb),
  FOREIGN KEY (IDKoncerta) REFERENCES KONCERT(IDKoncerta)
);

CREATE TABLE DEFINIRA
(
  IDIzvodaca INT NOT NULL,
  IDZanra INT NOT NULL,
  PRIMARY KEY (IDIzvodaca, IDZanra),
  FOREIGN KEY (IDIzvodaca) REFERENCES IZVODAC(IDIzvodaca),
  FOREIGN KEY (IDZanra) REFERENCES ZANR(IDZanra)
);

CREATE TABLE PRIPADAZANRU
(
  IDZanra INT NOT NULL,
  IDPjesme INT NOT NULL,
  PRIMARY KEY (IDZanra, IDPjesme),
  FOREIGN KEY (IDZanra) REFERENCES ZANR(IDZanra),
  FOREIGN KEY (IDPjesme) REFERENCES PJESMA(IDPjesme)
);